spring:
  profiles: pro
  application:
    name: config-single-client
  cloud:
     config:
       uri: http://localhost:3301
       label: master
       profile: pro

data:
  env: env-pro
  user:
    username: john-pro
    password: 123-pro
